# Generated by Django 3.2.3 on 2021-09-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_username', models.CharField(blank=True, db_column='error username', max_length=255, null=True)),
                ('error_password', models.CharField(blank=True, db_column='error password', max_length=255, null=True)),
            ],
            options={
                'db_table': 'error info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Logininformation',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'logininformation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MyStu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'my_stu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Studentbaseinformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=1)),
                ('subject', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'studentbaseinformation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=2)),
                ('ID_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Students',
                'managed': True,
            },
        ),
    ]
