# Generated by Django 3.2.3 on 2021-09-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorInfo',
        ),
    ]
